name: "jointdreamer_dmtet"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "./exps/3studio"
seed: 0

data_type: "random-multiview-camera-datamodule"
data:
  batch_size: 8
  n_view: 4
  width: 512
  height: 512
  resolution_milestones: [3000]
  camera_distance_range: [0.8, 1.0] # relative
  fovy_range: [25, 45]
  elevation_range: [0, 30]
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  eval_camera_distance: 3.0
  eval_fovy_deg: 45.
  n_val_views: 4


system_type: "jointdreamer-refine-system"
system:
  stage: texture
  guidance_eval_step: 1000
  geometry_convert_from: ???
  geometry_convert_inherit_texture: true
  geometry_type: "tetrahedra-sdf-grid"
  geometry:
    radius: 1.0 # consistent with coarse
    isosurface_resolution: 128
    isosurface_deformable_grid: true
    isosurface_outlier_n_faces_threshold: 0.0001
    isosurface_remove_outliers: true
    pos_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.447269237440378 # max resolution 4096
    fix_geometry: false # optimize grid sdf and deformation

  material_type: "diffuse-with-point-light-material"
  material:
    ambient_only_steps: 0
    textureless_prob: 0.5
    ambient_light_color: [1.0, 1.0, 1.0]
    diffuse_light_color: [0.0, 0.0, 0.0]
    soft_shading: true
    albedo_activation: sigmoid


  background_type: "neural-environment-map-background"
  background:
    color_activation: sigmoid
    random_aug: true
    eval_color: [0.66, 0.66, 0.66]
    share_aug_bg: true

  renderer_type: "nvdiff-rasterizer"
  renderer:
    context_type: gl

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: ???
    negative_prompt: "shadow, oversaturated, low quality, unrealistic, ugly, bad anatomy, blurry, pixelated obscure, unnatural colors, poor lighting, dull, and unclear, cropped, lowres, artifacts, duplicate, morbid, mutilated, poorly drawn face, deformed, dehydrated, bad proportions"
    front_threshold: 30.
    back_threshold: 30.

  guidance_type: "interview-diffusion-guidance-mvdream"
  guidance:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    guidance_scale: 70 #7.5
    weighting_strategy: "dreamfusion"
    min_step_percent: 0.02
    max_step_percent: 0.5
    guide: "load/jointdreamer/mvdream.yaml"
    extra_guid_wt: 5
    start_iter: 0
    cfg_rescale: 0.7


  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    lambda_sds: 1.
    lambda_orient: 0
    lambda_sparsity: 0
    lambda_opaque: 0.
    lambda_z_variance: 1.
    lambda_normal_consistency: 10000.
    lambda_laplacian_smoothness: 10000.

  optimizer:
    name: Adam
    args:
      lr: 0.001
      betas: [ 0.9, 0.99 ]
      eps: 1.e-15

trainer:
  max_steps: 5000
  log_every_n_steps: 1
  num_sanity_val_steps: 1
  val_check_interval: 200
  enable_progress_bar: true
  precision: 32

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
