name: "jointdreamer-refine"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "./exps/3studio"
seed: 0

data_type: "random-multiview-camera-datamodule"
data:
  batch_size: 4 # must be dividable by n_view
  n_view: 4
  # 0-4999: 64x64, >=5000: 512x512
  # this drastically reduces VRAM usage as empty space is pruned in early training
  width: 512
  height: 512
  resolution_milestones: [3000]
  camera_distance_range: [0.8, 1.0] # relative
  fovy_range: [15, 60]
  elevation_range: [0, 30]
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  eval_camera_distance: 3.0
  eval_fovy_deg: 40.
  n_val_views: 4


system_type: "jointdreamer-refine-system"
system:
  stage: coarse
  guidance_eval_step: 1000
  geometry_type: "implicit-volume"
  geometry:
    radius: 1.0
    normal_type: analytic

    density_bias: "blob_magic3d"
    density_activation: softplus
    density_blob_scale: 10.
    density_blob_std: 0.5

    pos_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.447269237440378 # max resolution 4096

  material_type: "diffuse-with-point-light-material"
  material:
    ambient_only_steps: 5000
    textureless_prob: 0.5
    ambient_light_color: [1.0, 1.0, 1.0]
    diffuse_light_color: [0.0, 0.0, 0.0]
    soft_shading: true
    albedo_activation: sigmoid


  background_type: "neural-environment-map-background"
  background:
    color_activation: sigmoid
    random_aug: true
    eval_color: [1, 1, 1]
    share_aug_bg: true

  renderer_type: "nerf-volume-renderer"
  renderer:
    radius: ${system.geometry.radius}
    num_samples_per_ray: 512

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: ???
    front_threshold: 30.
    back_threshold: 30.
    negative_prompt: "shadow, oversaturated, low quality, unrealistic, ugly, bad anatomy, blurry, pixelated obscure, unnatural colors, poor lighting, dull, and unclear, cropped, lowres, artifacts, duplicate, morbid, mutilated, poorly drawn face, deformed, dehydrated, bad proportions"

  guidance_type: "interview-diffusion-guidance-mvdream"
  guidance:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    guidance_scale: 50 #7.5
    weighting_strategy: "dreamfusion"
    min_step_percent: 0.05  # (start_iter, start_val, end_val, end_iter)
    max_step_percent: 0.5
    guide: "load/jointdreamer/mvdream.yaml"
    extra_guid_wt: 0
    start_iter: 600


#  exporter_type: "mesh-exporter"
#  exporter:
#    fmt: obj
#    save_uv: false
#    save_texture: true
#    context_type: cuda


  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    lambda_sds: 1
    lambda_orient: 0
    lambda_sparsity: 0
    lambda_opaque: 1.
    lambda_z_variance: 1
    lambda_normal_consistency: 0. # 10
    lambda_laplacian_smoothness: 0


  optimizer:
    name: AdamW
    args:
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry.encoding:
        lr: 0.000001
      geometry.density_network:
        lr: 0.000001
      geometry.feature_network:
        lr: 0.001
      background:
        lr: 0.001

trainer:
  max_steps: 6000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 200
  enable_progress_bar: true
#  precision: 32
  precision: 16-mixed

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: 1000
